// Central map of every trackable action in the system to a human-readable label.
// Used by both the Activity Feed (Reports page) and the full Audit Log page,
// so the two never show inconsistent wording for the same action.

export const ACTION_LABELS = {
  reservation_created: 'New Reservation',
  reservation_confirmed: 'Reservation Confirmed',
  reservation_cancelled: 'Reservation Cancelled',
  guest_checked_in: 'Guest Checked In',
  guest_checked_out: 'Guest Checked Out',
  charge_added: 'Charge Added',
  payment_recorded: 'Payment Recorded',
  refund_issued: 'Refund Issued',
  room_updated: 'Room Details Updated',
  room_cleaned: 'Room Cleaning Completed',
  housekeeper_assigned: 'Housekeeper Assigned',
  duty_scheduled: 'Duty Scheduled',
  duty_completed: 'Duty Completed',
  duty_removed: 'Duty Removed',
  maintenance_request_created: 'Maintenance Request Created',
  maintenance_assigned: 'Maintenance Request Assigned',
  maintenance_completed: 'Maintenance Request Completed',
  inventory_item_created: 'Inventory Item Created',
  stock_movement_recorded: 'Stock Movement Recorded',
  expense_recorded: 'Expense Recorded',
  staff_account_created: 'Staff Account Created',
  staff_role_changed: 'Staff Role Changed',
  staff_status_changed: 'Staff Status Changed',
  employee_profile_updated: 'Employee Profile Updated',
  roster_entry_created: 'Shift Scheduled',
  roster_week_duplicated: 'Weekly Schedule Duplicated',
  roster_entry_removed: 'Shift Removed',
  staff_clocked_in: 'Clocked In',
  staff_clocked_out: 'Clocked Out',
  task_assigned: 'Task Assigned',
  task_status_updated: 'Task Status Updated',
  task_verified: 'Task Verified',
  task_removed: 'Task Removed',
  checklist_completed: 'Checklist Completed',
  leave_requested: 'Leave Requested',
  leave_cancelled: 'Leave Cancelled',
  leave_approved: 'Leave Approved',
  leave_rejected: 'Leave Rejected',
  document_uploaded: 'Document Uploaded',
  document_deleted: 'Document Deleted',
  training_recorded: 'Training Recorded',
  training_removed: 'Training Removed',
  meeting_created: 'Meeting Recorded',
  action_item_converted_to_task: 'Action Item Converted to Task',
  disciplinary_record_created: 'Disciplinary Record Created',
  disciplinary_record_updated: 'Disciplinary Record Updated',
};

export function labelForAction(action) {
  return ACTION_LABELS[action] ?? action.replace(/_/g, ' ');
}